call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" vim behaves like vim and not vi
set nocompatible

syntax on
set mouse=nv
" Hide mouse when typing
set mousehide

set background=dark
colorscheme solarized

filetype plugin indent on

" status bar
set laststatus=2
" display line and char count in status bar
set ruler
" display line numbers
set number
" allow buffers to exist without being written to disk
set hidden

if has("wildmenu")
    set wildignore+=*.a,*.o
    set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png
    set wildignore+=.git,.hg,.svn
    set wildignore+=*~,*.swp,*.tmp
    set wildmenu
    set wildmode=longest:full,full
endif

let NERDTreeIgnore=['\.pyc']

if has("autocmd")
  autocmd BufNewFile,BufRead *.rss setfiletype xml
endif

if exists('+colorcolumn')
  set colorcolumn=81
else
  au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>81v.\+', -1)
endif

set spelllang=eng_US
