call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" vim behaves like vim and not vi
set nocompatible

syntax on
set mouse=nv
" Hide mouse when typing
set mousehide

set background=dark
colorscheme solarized

if has("autocmd")
    filetype plugin indent on
endif

" display status bar
set laststatus=2
" display line and char count in status bar
set ruler
" display line numbers
set number
" allow buffers to exist without being written to disk
set hidden
" interactively search for expression
set incsearch
" smoother redraw for faster terms
set ttyfast
" minimum number of lines to display around the curser line
if !&scrolloff
    set scrolloff=2
endif
" Highlight VCS conflict markers
match ErrorMsg '^\(<\|=\|>\)\{7\}\([^=].\+\)\?$'


" allow modelines to be used; for files that have to declare their type as a
" comment
set modeline

" Find files recusively in current directory
set path+=**
" Don't have to look for suffixes in find
set suffixesadd=.rb,.py,.coffee,.js,.sh,.sass,.scss,.html,.erb,.css,.java,.C
set suffixesadd+=.cc,.CPP,.cxx,.c++,.cpp,.H,.hh,.HPP,.hxx,.h++,.hpp,.tcc,.c,.h
set suffixesadd+=.s,.S

" Hidden tags file
set tags+=.tags

" wildmenu setup (tab completion with a builtin popup menu)
" the wildmenu is a single line
" wildmode is semi-fuzzy matching
if has("wildmenu")
    " Compiled files
    set wildignore+=*.a,*.o
    set wildignore+=*.class,*.pyc
    " Images
    set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png
    " VCS stuff
    set wildignore+=.git,.hg,.svn
    " temperary files and tags files
    set wildignore+=*~,*.swp,*.tmp,.tags,tags
    " LaTeX crap
    set wildignore+=*.log,*.aux,*.dvi,*.aut,*.bbl,*.blg,*.fff,*.out,*.pdf,*.ps
    set wildignore+=*.toc,*.ttt

    set wildmenu
    set wildmode=longest:full,full
endif

" rss is xml
if has("autocmd")
  autocmd BufNewFile,BufRead *.rss setfiletype xml
endif

" Mark past 80 columns
if exists('+colorcolumn')
  set colorcolumn=81
else
  au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>81v.\+', -1)
endif

set spelllang=eng_US
