" vim:filetype=vim

" vim behaves like vim and not vi
set nocompatible

call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

syntax on
if has("autocmd")
    filetype plugin indent on
endif

" display status bar
set laststatus=2
" display line and char count in status bar
set ruler
" display line numbers
set number
" allow buffers to exist without being written to disk
set hidden
set encoding=utf-8
" highlight search terms; :noh to clear
set hlsearch
" interactively search for expression
set incsearch
" smoother redraw for faster terms
set ttyfast
" faster escape into modes
set timeoutlen=400
set ttimeoutlen=50
" let OS decide when to sync
set nofsync
" don't need weird redraw times
set lazyredraw
" minimum number of lines to display around the curser line
set scrolloff=3
set sidescrolloff=3
" allow visual block mode to not care about chars not being there
set virtualedit
" sane defaults for windows splits
set splitbelow
set splitright
" show title in console bar
set title
" mouse in normal and visual mode
set mouse=nv
" Hide mouse when typing
set mousehide
" backspace works like normal
set backspace=indent,eol,start
" use system clipboard
set clipboard=unnamed
" commandline history
set history=1000
" so cursor stays in same column after commands: CTRL-D, CTRL-U, CTRL-B, CTRL-F,
"   'G', 'H', 'M', 'L', gg, etc
set nostartofline
" only allow certain functions in cur dir vimrc's
set secure
"   allow vimrc settings in dir where vim is launched; .exrc .vimrc .gvimrc
"   set exrc
" allow modelines; files can declare options as a comment; # vim: noai:bla tw=2
set modeline
" switch to a window in which a buffer is already open
set switchbuf=useopen
" just one space for line joins, even after punctuation
set nojoinspaces
" Know what just happened, no matter the amount of lines changed
set report=0
" show extra info on right side of command line
set showcmd

" for spell checking
if exists("+spelllang")
  set spelllang=en_US
endif

" TODO: sane viminfo defaults
" Marks are saved for the past 100 files
set viminfo='100
" number of searches to save, max
set viminfo+=/1000
" number of commands to save, max
set viminfo+=:1000
" number of lines saved for each register, max
set viminfo+=<500
" number of lines in input history to be saved, max
set viminfo+=@500
" size in kb for registers to be saved, max
set viminfo+=s1000
" ignore these directory paths
set viminfo+=r/tmp,r/mnt/cdrom
" viminfo is in .vim folder
set viminfo+=n~/.vim/viminfo

" character to show if a line is wrapped
if exists('breakpoint')
  set showbreak=↪
endif
" <xx> as non-print characters instead of control style characters
set display=uhex

set background=dark
colorscheme base16-monokai
" force 256 term
set t_Co=256
" don't clear terminal background
set t_ut=

" Highlight VCS conflict markers
match ErrorMsg '^\(<\|=\|>\)\{7\}\([^=].\+\)\?$'
" Mark past 80 columns
if exists('+colorcolumn')
  set colorcolumn=81
else
  au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>81v.\+', -1)
endif

" TODO: LESS PINKIE HURT!!!!
" undo? waiting on undo since open
" if has("persistant_undo")
"   set undofile
"   set undolevel=1000
" endif
" set autowriteall
" set autoread

" Find files recusively in current directory
set path+=**
" Don't have to look for suffixes in find
set suffixesadd=.rb,.py,.coffee,.js,.sh,.sass,.scss,.html,.erb,.css,.java,.C
set suffixesadd+=.cc,.CPP,.cxx,.c++,.cpp,.H,.hh,.HPP,.hxx,.h++,.hpp,.tcc,.c,.h
set suffixesadd+=.s,.S

" Hidden tags file
set tags+=.tags;

" wildmenu setup (tab completion with a builtin popup menu)
" the wildmenu is a single line
" wildmode is semi-fuzzy matching
if has("wildmenu")
    " Compiled files
    set wildignore+=*.a,*.o
    set wildignore+=*.class,*.pyc
    " Images
    set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png
    " VCS stuff
    set wildignore+=.git,.hg,.svn
    " temperary files and tags files
    set wildignore+=*~,*.swp,*.tmp,.tags,tags
    " LaTeX crap
    set wildignore+=*.log,*.aux,*.dvi,*.aut,*.bbl,*.blg,*.fff,*.out,*.pdf,*.ps
    set wildignore+=*.toc,*.ttt

    set wildmenu
    set wildmode=longest:full,full
endif

" synonyms for filetypes
if has("autocmd")
  autocmd BufNewFile,BufRead *.rss setfiletype xml
  autocmd BufNewFile,BufRead *.json setfiletype javascript
endif

let g:ctrlp_cmd = "CtrlPMixed"
let g:delimitMate_offByDefault = 1

" syntastic good configs
let g:syntastic_aggregate_errors = 1
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_python_pylint_exe = "pylint"
let g:syntastic_error_symbol = '✗'
let g:syntastic_warning_symbol = '⚠'
let g:syntastic_style_error_symbol = '⚡'
let g:syntastic_style_warning_symbol = '⚡'
let g:syntastic_check_on_open=1

" netrw treeview
let g:netrw_liststyle = 3

" for textobj-rubyblock
runtime macros/matchit.vim

" Plugin TODO:
" vim-signature " <- show marks next to line numbers
" tpope/vim-vinegar.git
" Shougo/unite.vim " depends on Shougo/vimproc.vim
" youcompleteme
" unit plugins?
" vimez/vim-tmux or zepto/unite-tmux or vim-tmux-navigator
" majutsushi/tagbar
" elera/vim-javascript-syntax
" pangloss/vim-javascript
" marijnh/tern_for_vim " <- awesome js linter/checker/parser
" let g:rubycomplete_buffer_loading=1
" let g:rubycomplete_classes_in_global=1
" let g:rubycomplete_rails=1
"
" follow up reading from: http://www.infoq.com/presentations/Vim-From-Essentials-to-Mastery
" Capital letter appends to register
" CTRL-R register, CTRL-R CTRL-R, CTRL-R CTRL-O, CTRL-R CTRL-P
" registers: ": "1-9 (stack of delete history) "/ "! ". (last inserted text) "% (current file) "# (alt
"   file) "_ (blackhole) "= (expressions, can use math expressions)
" use rdoc, pydoc instead of man
" ex commands
" nmap & run last substitute, s///& (keep flags from last substitute)
" zz, zt, zb (move window around cursor)
" !<motion> !! (filter line through program)
" | (go to column)
" ; , used with t,T,f,F to repeat forward and backward
" preload registers in vimrc like let @d = strftime("%c")
" search when loaded let @/ = "search term"
" execute accidentally inserted command ^[ u@.
" combine registers let @a = @a . @b . @c
" capture output to a register redir @A
" yank matches into register :g/pattern/y A (uppercase is important)
" g< displays last command output
" q: q/ in nomral mode bring up history windows, CTRL-F when already in them
"
" map motion commands
"   CTRL-H CTRL-J CTRL-N CTRL-M CTRL-L (currently redraw) <Backspace>
"
" keys that totally need remapping:
"   <space> <cr> <C-space> CTRL-CR <Backspace> <C-Backspace>
" Need readline shortcuts in insert/command
