#!/bin/zsh
# vi:filetype=sh

testtype () {
    type "$1" &> /dev/null
}

# Init xinit programs
if [ -d /etc/X11/xinit/xinitrc.d ]
then
    for f in /etc/X11/xinit/xinitrc.d/*
    do
        [ -x "$f" ] && . "$f"
    done

    unset f
fi

if testtype xinput
then
    if (xinput list 'SynPS/2 Synaptics TouchPad' &> /dev/null) \
        && (xinput list 'TPPS/2 IBM TrackPoint' &> /dev/null)
    then
        touchpad_id="$(xinput list --id-only 'SynPS/2 Synaptics TouchPad')"
        xinput disable "${touchpad_id}"
    fi
fi

# For Chrome proxy settings
# export DESKTOP_SESSION=gnome

XDG_CACHE_HOME="${XDG_CACHE_HOME:-${HOME}/.cache}"
awesome_cache="${XDG_CACHE_HOME}"/awesome/
if ! [ -e "${awesome_cache}" ]
then
    mkdir --mode 0700 "${awesome_cache}"
    awesome_stdout="${awesome_cache}/stdout.log"
    awesome_stderr="${awesome_cache}/stderr.log"
elif ! [ -d "${awesome_cache}" ]
then
    awesome_stdout=/dev/null
    awesome_stderr=/dev/null
fi

unset -f testtype

exec awesome #>> "${awesome_stdout}" 2>> "${awesome_stderr}"
