#!/bin/zsh
# vi:filetype=sh

testtype () {
    type "$1" &> /dev/null
}

# Init xinit programs
if [ -d /etc/X11/xinit/xinitrc.d ]
then
    for f in /etc/X11/xinit/xinitrc.d/*
    do
        [ -x "$f" ] && . "$f"
    done

    unset f
fi

if testtype xinput
then
    if (xinput list 'SynPS/2 Synaptics TouchPad' &> /dev/null) \
        && (xinput list 'TPPS/2 IBM TrackPoint' &> /dev/null)
    then
        touchpad_id="$(xinput list --id-only 'SynPS/2 Synaptics TouchPad')"
        xinput disable "${touchpad_id}"
    fi
fi

# For Chrome proxy settings
# export DESKTOP_SESSION=gnome

unset -f testtype
